
CREATE INDEX matrimony_attempts_ip_time ON public.matrimony_attempts USING btree (ip, attempted_at DESC);
CREATE INDEX matrimony_photos_sort ON public.matrimony_photos USING btree (category, sort_order);
CREATE INDEX matrimony_quiz_options_question_idx ON public.matrimony_quiz_options USING btree (question_id);

CREATE TRIGGER matrimony_config_updated_at BEFORE UPDATE ON public.matrimony_config FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER matrimony_photos_updated_at BEFORE UPDATE ON public.matrimony_photos FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER posts_updated_at BEFORE UPDATE ON public.posts FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER trg_anime_updated BEFORE UPDATE ON public.anime_items FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER trg_design_works_updated BEFORE UPDATE ON public.design_works FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER trg_matrimony_quiz_options_updated_at BEFORE UPDATE ON public.matrimony_quiz_options FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER trg_matrimony_quiz_questions_updated_at BEFORE UPDATE ON public.matrimony_quiz_questions FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER trg_matrimony_skills_updated_at BEFORE UPDATE ON public.matrimony_skills FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER trg_movies_updated BEFORE UPDATE ON public.movies FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER trg_music_updated BEFORE UPDATE ON public.music_items FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER trg_poems_updated BEFORE UPDATE ON public.poems FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER trg_site_settings_updated BEFORE UPDATE ON public.site_settings FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_matrimony_achievements_updated_at BEFORE UPDATE ON public.matrimony_achievements FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_matrimony_family_nodes_updated_at BEFORE UPDATE ON public.matrimony_family_nodes FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_matrimony_testimonials_updated_at BEFORE UPDATE ON public.matrimony_testimonials FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

CREATE POLICY "Admins delete contact messages" ON public.contact_messages FOR DELETE TO authenticated USING (public.is_admin(auth.uid()));
CREATE POLICY "Admins read all anime" ON public.anime_items FOR SELECT TO authenticated USING (public.is_admin(auth.uid()));
CREATE POLICY "Admins read all design works" ON public.design_works FOR SELECT TO authenticated USING (public.is_admin(auth.uid()));
CREATE POLICY "Admins read all movies" ON public.movies FOR SELECT TO authenticated USING (public.is_admin(auth.uid()));
CREATE POLICY "Admins read all music" ON public.music_items FOR SELECT TO authenticated USING (public.is_admin(auth.uid()));
CREATE POLICY "Admins read all poems" ON public.poems FOR SELECT TO authenticated USING (public.is_admin(auth.uid()));
CREATE POLICY "Admins read audit logs" ON public.audit_logs FOR SELECT TO authenticated USING (public.is_admin(auth.uid()));
CREATE POLICY "Admins read contact messages" ON public.contact_messages FOR SELECT TO authenticated USING (public.is_admin(auth.uid()));
CREATE POLICY "Admins update contact messages" ON public.contact_messages FOR UPDATE TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
CREATE POLICY "Anyone can send a message" ON public.contact_messages FOR INSERT TO authenticated, anon WITH CHECK (((name IS NOT NULL) AND ((length(name) >= 1) AND (length(name) <= 200)) AND (email IS NOT NULL) AND ((length(email) >= 3) AND (length(email) <= 320)) AND (email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$'::text) AND (message IS NOT NULL) AND ((length(message) >= 1) AND (length(message) <= 5000))));
CREATE POLICY "Editors insert anime" ON public.anime_items FOR INSERT TO authenticated WITH CHECK (public.is_editor_or_above(auth.uid()));
CREATE POLICY "Editors insert design works" ON public.design_works FOR INSERT TO authenticated WITH CHECK (public.is_editor_or_above(auth.uid()));
CREATE POLICY "Editors insert movies" ON public.movies FOR INSERT TO authenticated WITH CHECK (public.is_editor_or_above(auth.uid()));
CREATE POLICY "Editors insert music" ON public.music_items FOR INSERT TO authenticated WITH CHECK (public.is_editor_or_above(auth.uid()));
CREATE POLICY "Editors insert poems" ON public.poems FOR INSERT TO authenticated WITH CHECK (public.is_editor_or_above(auth.uid()));
CREATE POLICY "Editors insert posts" ON public.posts FOR INSERT TO authenticated WITH CHECK (public.is_editor_or_above(auth.uid()));
CREATE POLICY "Editors read all posts" ON public.posts FOR SELECT TO authenticated USING (public.is_editor_or_above(auth.uid()));
CREATE POLICY "Editors update anime" ON public.anime_items FOR UPDATE TO authenticated USING (public.is_editor_or_above(auth.uid())) WITH CHECK (public.is_editor_or_above(auth.uid()));
CREATE POLICY "Editors update design works" ON public.design_works FOR UPDATE TO authenticated USING (public.is_editor_or_above(auth.uid())) WITH CHECK (public.is_editor_or_above(auth.uid()));
CREATE POLICY "Editors update movies" ON public.movies FOR UPDATE TO authenticated USING (public.is_editor_or_above(auth.uid())) WITH CHECK (public.is_editor_or_above(auth.uid()));
CREATE POLICY "Editors update music" ON public.music_items FOR UPDATE TO authenticated USING (public.is_editor_or_above(auth.uid())) WITH CHECK (public.is_editor_or_above(auth.uid()));
CREATE POLICY "Editors update poems" ON public.poems FOR UPDATE TO authenticated USING (public.is_editor_or_above(auth.uid())) WITH CHECK (public.is_editor_or_above(auth.uid()));
CREATE POLICY "Editors update posts" ON public.posts FOR UPDATE TO authenticated USING (public.is_editor_or_above(auth.uid())) WITH CHECK (public.is_editor_or_above(auth.uid()));
CREATE POLICY "Editors update site settings" ON public.site_settings FOR UPDATE TO authenticated USING (public.is_editor_or_above(auth.uid())) WITH CHECK (public.is_editor_or_above(auth.uid()));
CREATE POLICY "Editors upsert site settings" ON public.site_settings FOR INSERT TO authenticated WITH CHECK (public.is_editor_or_above(auth.uid()));
CREATE POLICY "Public read published anime" ON public.anime_items FOR SELECT TO authenticated, anon USING (((status = 'published'::public.content_status) AND (deleted_at IS NULL)));
CREATE POLICY "Public read published design works" ON public.design_works FOR SELECT TO authenticated, anon USING (((status = 'published'::public.content_status) AND (deleted_at IS NULL)));
CREATE POLICY "Public read published movies" ON public.movies FOR SELECT TO authenticated, anon USING (((status = 'published'::public.content_status) AND (deleted_at IS NULL)));
CREATE POLICY "Public read published music" ON public.music_items FOR SELECT TO authenticated, anon USING (((status = 'published'::public.content_status) AND (deleted_at IS NULL)));
CREATE POLICY "Public read published poems" ON public.poems FOR SELECT TO authenticated, anon USING (((status = 'published'::public.content_status) AND (deleted_at IS NULL)));
CREATE POLICY "Public read published posts" ON public.posts FOR SELECT TO authenticated, anon USING ((published = true));
CREATE POLICY "Public read site settings" ON public.site_settings FOR SELECT TO authenticated, anon USING (true);
CREATE POLICY "Super admins can view matrimony attempts" ON public.matrimony_attempts FOR SELECT TO authenticated USING (public.is_super_admin(auth.uid()));
CREATE POLICY "Super admins delete admin roles" ON public.admin_roles FOR DELETE TO authenticated USING (public.is_super_admin(auth.uid()));
CREATE POLICY "Super admins delete anime" ON public.anime_items FOR DELETE TO authenticated USING (public.is_super_admin(auth.uid()));
CREATE POLICY "Super admins delete design works" ON public.design_works FOR DELETE TO authenticated USING (public.is_super_admin(auth.uid()));
CREATE POLICY "Super admins delete movies" ON public.movies FOR DELETE TO authenticated USING (public.is_super_admin(auth.uid()));
CREATE POLICY "Super admins delete music" ON public.music_items FOR DELETE TO authenticated USING (public.is_super_admin(auth.uid()));
CREATE POLICY "Super admins delete poems" ON public.poems FOR DELETE TO authenticated USING (public.is_super_admin(auth.uid()));
CREATE POLICY "Super admins delete posts" ON public.posts FOR DELETE TO authenticated USING (public.is_super_admin(auth.uid()));
CREATE POLICY "Super admins delete site settings" ON public.site_settings FOR DELETE TO authenticated USING (public.is_super_admin(auth.uid()));
CREATE POLICY "Super admins insert admin roles" ON public.admin_roles FOR INSERT TO authenticated WITH CHECK (public.is_super_admin(auth.uid()));
CREATE POLICY "Super admins manage achievements" ON public.matrimony_achievements USING (public.is_super_admin(auth.uid())) WITH CHECK (public.is_super_admin(auth.uid()));
CREATE POLICY "Super admins manage family nodes" ON public.matrimony_family_nodes USING (public.is_super_admin(auth.uid())) WITH CHECK (public.is_super_admin(auth.uid()));
CREATE POLICY "Super admins manage matrimony config" ON public.matrimony_config TO authenticated USING (public.is_super_admin(auth.uid())) WITH CHECK (public.is_super_admin(auth.uid()));
CREATE POLICY "Super admins manage matrimony photos" ON public.matrimony_photos TO authenticated USING (public.is_super_admin(auth.uid())) WITH CHECK (public.is_super_admin(auth.uid()));
CREATE POLICY "Super admins manage testimonial invites" ON public.matrimony_testimonial_invites USING (public.is_super_admin(auth.uid())) WITH CHECK (public.is_super_admin(auth.uid()));
CREATE POLICY "Super admins manage testimonials" ON public.matrimony_testimonials USING (public.is_super_admin(auth.uid())) WITH CHECK (public.is_super_admin(auth.uid()));
CREATE POLICY "Super admins read all admin roles" ON public.admin_roles FOR SELECT TO authenticated USING (public.is_super_admin(auth.uid()));
CREATE POLICY "Super admins update admin roles" ON public.admin_roles FOR UPDATE TO authenticated USING (public.is_super_admin(auth.uid())) WITH CHECK (public.is_super_admin(auth.uid()));
CREATE POLICY "Users can insert their own profile" ON public.profiles FOR INSERT WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can update their own profile" ON public.profiles FOR UPDATE USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own profile" ON public.profiles FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users read own admin role" ON public.admin_roles FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "super admins manage matrimony_quiz_options" ON public.matrimony_quiz_options TO authenticated USING (public.is_super_admin(auth.uid())) WITH CHECK (public.is_super_admin(auth.uid()));
CREATE POLICY "super admins manage matrimony_quiz_questions" ON public.matrimony_quiz_questions TO authenticated USING (public.is_super_admin(auth.uid())) WITH CHECK (public.is_super_admin(auth.uid()));
CREATE POLICY "super admins manage matrimony_skills" ON public.matrimony_skills TO authenticated USING (public.is_super_admin(auth.uid())) WITH CHECK (public.is_super_admin(auth.uid()));
